#设置端口为9090
server:
  port: 9090
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway-server
  #配置SpringCloudGateway的路由
  cloud:
    gateway:
      routes:
        - id: user-service  #id是自定义的标识
          uri: lb://userService  #当访问9090端口时，自动把ip和端口替换为此uri
          predicates:
            - Path=/user/**  #自动匹配/user/**的路径
#          filters:
#            - name: RequestRateLimiter
#              args:
#                #使用SpEL从Spring容器中获取对象
#                key-resolver: '#{@pathKeyResolver}'
#                #令牌桶每秒填充的平均速率
#                redis-rate-limiter.replenishRate: 1
#                #令牌桶的容量
#                redis-rate-limiter.burstCapacity: 3
    discovery:
      locator:
        enabled: true #开启根据微服务名称自动转发
        lower-case-service-id: true  #w微服务名称小写呈现


